### ISSUE TITLE
failed to install loomR

### ISSUE THREAD

**Issue by Sophia409** [mojaveazure/loomR#29]
> devtools::install_github(repo = 'mojaveazure/loomR', ref = 'develop')
Skipping install of 'loomR' from a github remote, the SHA1 (f52d0b77) has not changed since last install.
  Use `force = TRUE` to force installation
Can you help me with it?
![image](https://user-images.githubusercontent.com/30619010/52909767-ad120c80-32c8-11e9-8759-98a237e71a05.png)

**Comment by mschilli87** [comment]
This simply means that the same version already is installed.
Setting `force = TRUE` will re-install it regardless.

**Comment by Sophia409** [comment]
@mschilli87 
hello, thank you for your reply.May I ask you another question?
I failed to install hdf5r using this command provided by https://satijalab.org/seurat/mca_loom.html: devtools::install_github(repo = 'hhoeflin/hdf5r'),below is the code,can you help me ?
![image](https://user-images.githubusercontent.com/30619010/52910146-2c560f00-32ce-11e9-9195-f4748f9f06cb.png)

![image](https://user-images.githubusercontent.com/30619010/52910141-22341080-32ce-11e9-910f-c9b5c8b1a1be.png)

![image](https://user-images.githubusercontent.com/30619010/52910131-07fa3280-32ce-11e9-8a6b-59823801c23f.png)

**Comment by mschilli87** [comment]
@Sophia409: If you take the time to

i) configure your system to give English output only, and
ii) copy paste the text as formatted code blocks

so I can

a) read, and
b) copy/paste it,

 I can have a look.

---
Note however, that this seems to belong to another repository as it is not a loomR error: https://github.com/hhoeflin/hdf5r/issues

Finally, after you close this issue and before you open a new one, please check the issues there (38 open and 49 closed) in case this problem is already known (or even resolved).

**Comment by Sophia409** [comment]
@mschilli87 thank you, I will.And can you tell me how to configure my system to give English output only?
